[target.aarch64-linux-android]
linker = "/home/pankaj/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android34-clang"
ar = "/home/pankaj/android-ndk-r26c/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
