[package]
name = "kokoros-android"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros"] }
kokoros = { path = "../kokoros" }